[package]
name = "xlang_compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xlang_core = { path = "../xlang_core" }
xlang_vm = { path = "../xlang_vm" }